
#En este archivo se generan las documentaciones para las mitades de los teclados,
#con sus configuraciones determinadas en este ejemplo se generan las dos mitades de Sofle con
#Nice nano V2

---
include:
  - board: nice_nano_v2
    shield: sofle_left
  - board: nice_nano_v2
    shield: sofle_right
